secret-service:
  image: nginx


jwt-proxy:
  image: jwt-proxy
  ports:
    - 6001:6001
  links:
    - secret-service:backend
  environment:
    - ASPNETCORE_URLS=http://*:6001
    - ProxySettings:Mode=Http403
    - ProxySettings:BackendHost=backend
    - ProxySettings:BackendPort=8080
    - ProxySettings:BackendScheme=http
    - ProxySettings:RequiredKeys:0:Key=role
    - ProxySettings:RequiredKeys:0:Value=admin
